<?php
/**
 * Product Units and Quantities
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitunits
 * @version      1.0.11
 * @license:     0JdTQfDMswel7fbpH42tkXIHe3fixI4GH3daX0aDVf
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
if($this->hasContainer()): ?>
        <div id="aitunits_qty_container_<?php echo $this->getId(); ?>" class="aitunits-select-container aitunits-dropdown-box" >
<?php endif; ?>
    
<?php if($this->hasContainer()): ?>
        </div>
<?php endif; ?>