<?php
/**
 * All-In-One Checkout v1.0.15 : All-In-One Checkout v1.0.15 (OPCB Unit)
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitcheckout / Aitoc_Aitcheckout
 * @version      1.0.15 - 1.4.15
 * @license:     jC7sr77MwqoHj2SDR8w4YXR3o3w7irXLNFUdRYpgyc
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<ul class="form-list">
<?php foreach($this->getFields() as $field): ?>
    <li>
        <div class="input-box">
		<?php echo $field->getHtml() ?>
		<div>
	</li>
<?php endforeach?>
</ul> 
<script type="text/javascript">
//<![CDATA[

    aitCheckout.createStep('deliverydate',{
            }, {
                doCheckErrors : false,
                isLoadWaiting : false,
                isUpdateOnReload : false,
                container: 'checkout-step-deliverydate'
            }
    );

//]]>
</script>