<?php
/**
 * MageParts
 *
 * NOTICE OF LICENSE
 *
 * This code is copyrighted by MageParts and may not be reproduced
 * and/or redistributed without a written permission by the copyright
 * owners. If you wish to modify and/or redistribute this file please
 * contact us at info@mageparts.com for confirmation before doing
 * so. Please note that you are free to modify this file for personal
 * use only.
 *
 * If you wish to make modifications to this file we advice you to use
 * the "local" file scope in order to aviod conflicts with future updates.
 * For information regarding modifications see http://www.magentocommerce.com.
 *
 * DISCLAIMER
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category   MageParts
 * @package    MageParts_Ddq
 * @copyright  Copyright (c) 2009 MageParts (http://www.mageparts.com/)
 * @author     MageParts Crew
 */
?>
<?php /* @var $this MageParts_Ddq_Block_Ddq */  ?>

<?php $jsonConfig = $this->getJsConfig() ?>
<?php $products = $this->_getProducts() ?>


<?php if (count($products)): ?>
    <?php foreach ($products as $product): ?>
    <?php $id = $product->getDdqId() ? $product->getDdqId() : $product->getId() ?>
    <span id="mp-ddq-el-<?php echo $id ?>" class="mp-ddq-el">
        <?php if ($product->getDdqLayout() == 'table'): ?>
            <?php $cols = Mage::helper('ddq')->getLayoutTableColumns() ?>
            <?php if (count($cols)): ?>
                <table id="mp-ddq-el-<?php echo $id ?>-<?php echo $product->getDdqLayout()?>" class="data-table" style="display:none;" data-mp-ddq="">
                    <thead>
                    <?php foreach ($cols as $col): ?>
                        <th><?php echo $col['title'] ?></th>
                    <?php endforeach; ?>
                    </thead>
                    <tbody>
                    <?php foreach ($product->getDdqQtyList() as $o): ?>
                        <?php echo $this->getTableRow($product, $o) ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        <?php else: ?>
        <select id="mp-ddq-el-<?php echo $id ?>-<?php echo $product->getDdqLayout() ?>" style="display:none;" data-mp-ddq="" disabled>
            <?php if (Mage::getStoreConfigFlag('ddq/layout/select_header', $product->getStoreId())): ?>
            <option value="0"><?php echo Mage::getStoreConfig('ddq/layout/select_header_text', $product->getStoreId()) ?></option>
            <?php endif; ?>
            <?php foreach ($product->getDdqQtyList() as $o): ?>
            <option value="<?php echo $o['qty'] ?>"<?php if ($product->getDdqPreselected() == $o['qty']): ?> selected<?php endif; ?>><?php echo Mage::helper('ddq')->getOptionLabel($o, $product) ?></option>
            <?php endforeach; ?>
        </select>
        <?php endif; ?>
    </span>
    <?php endforeach; ?>

    <?php if (!$this->getAvoidJsInstance()): ?>
    <script type="text/javascript">
        //<![CDATA[
        (function() {
            var config = <?php echo $jsonConfig ?>;
            var view   = MP_DDQ_SETTINGS.view;

            if (view === 'list') {
                new MageParts.Ddq.ProductList(config);
            }
            else if (view === 'cart') {
                new MageParts.Ddq.Cart(config);
            }
            else {
                switch(config.productType) {
                    case 'simple'       : new MageParts.Ddq.Product(config); break;
                    case 'grouped'      : new MageParts.Ddq.Grouped(config); break;
                    case 'bundle'       : new MageParts.Ddq.Bundle(config);  break;
                    case 'configurable' : new MageParts.Ddq.Configurable(config); break;
                }
            }
        }());
        //]]>
    </script>
    <?php endif; ?>
<?php else: ?>
    <?php // hide normal quantity text box element before it's replaced by javascript (prevents element from blinking into view on page load)?>
    <?php $paths = Mage::getBlockSingleton('ddq/general')->getCssRemovalPaths(true) ?>
    <?php if (!empty($paths)): ?>
        <style type="text/css">
            <?php echo $paths ?> { display:inline-block; }
        </style>
    <?php endif; ?>
<?php endif; ?>
