<?php
/**
 * Product Units and Quantities
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitunits
 * @version      1.0.11
 * @license:     0JdTQfDMswel7fbpH42tkXIHe3fixI4GH3daX0aDVf
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<script type="text/javascript">
    <?php if($this->isRenderBlock()): ?>
        var aitunitsUnitBlock = new aitunitsUnitHelper(<?php echo $this->getJsParams();?> );
        aitunitsUnitBlock.render();
    <?php endif; ?> 
</script>