<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
$_product = $this->getProduct();
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    var productFormData = '<?php echo http_build_query($this->getProductOptionsData()); // Get the stored POST data to allow page refresh ?>';
    var actionName = '<?php echo Mage::app()->getRequest()->getActionName(); ?>';
    var isLoggedIn = '<?php echo $this->helper('customer')->isLoggedIn(); ?>';


    var frameWindow = null;
    var editor = null;
    var fullyLoaded = false;
</script>





<div id="messages_product_view">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div class="product-view">
<div class="product-essential">


<!---TOP EDITOR BUTTONS-->
<form action="<?php echo $this->getChiliAddToCartUrl($_product->getId()) ?>" method="post" id="product_addtocart_form" <?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
    <input type="hidden" name="related_product" id="related-products-field" value="" />
    <input type="hidden" name="product_id" id="product_id" value="<?php echo $_product->getId(); ?>" />
    <input type="hidden" name="chili_document_id" id="chili_document_id" value="<?php echo $this->getChiliDocumentId(); ?>" style="width:100px"/>
    <input type="hidden" name="qty" id="qty" value="<?php echo ($this->getRequest()->getParam('qty')) ? $this->getRequest()->getParam('qty') : $_product->getStockItem()->getMinSaleQty(); ?>" />
	<div class="editor-links">   
	<!-----------------------Left Buttons-------------------------->
		<div class="left">
            <span>
				<button type="button" class="button btn-cart" >
					<span>
						<a href="javascript:history.go(-1)" style="color:#fff" title="<?php echo $this->__('Back'); ?>" class="">&lt;&lt; <?php echo $this->__('Back'); ?></a>
					</span>
				</button>
				<div id="navigation">
					<h3 id="headerNav"><?php echo Mage::helper('web2print')->__('Navigation'); ?></h3>
				</div>
			</span>
		</div>
	<!-----------------------Right Buttons-------------------------->		
        <div class="right">
            <?php if (count($_product->getOptions()) >= 1) { ?>
                <button type="button" class="button btn-cart" >
					<span>
                    	<a href="#" class="actionLink" title="<?php echo $this->__('Configure options'); ?>" id="configure-options" style="color:#fff;"><?php echo $this->__('Configure Options'); ?></a>
					</span>
				</button>
                <div id="productOptions" style="position:absolute!important; display:none;">
                     <div id="product-options-container" >
                            <?php
                            if ($this->hasOptions()):
                                echo $this->getChildHtml('product_options_wrapper');
                            endif; ?>
                            <button type="button" title="<?php echo $this->__('Save print options'); ?>" class="button btn-cart" id="save-options">
                                <span>
                                    <span><?php echo $this->__('Save print options'); ?></span>
                                </span>
                            </button>
                     </div>
                 </div>
            <?php } ?>
			
     		<?php echo $this->getConceptActionButtonHtml(); ?>



<!--Original Share URL Button
           <button type="button" class="button btn-cart" >
				<span>
					<a href="<?php echo $this->getChiliEditorUrl(); ?>" class="button btn-cart" style="color:#fff" title="Share Design" id="button btn-cart" target="_blank"><?php echo $this->__('Share URL'); ?></a>
				</span>
			</button>
ends here-->

            <span>
                <?php echo $this->getShoppingcartActionButtonHtml(); ?>
            </span>
        </div>
    </div>
</form>

<?php
    if (isset($_POST['colabToEmail']) && isset($_POST['colabFromEmail'])) {
        $colabToEmail = $_POST['colabToEmail'];
        $colabFromEmail = $_POST['colabFromEmail'];
        $chili_url = $_POST['chili_url'];

        if (!empty($colabToEmail) && !empty($colabFromEmail)) {
            $to = $colabToEmail;
            $subject = 'Colaborate with me on this item from Finelink 2.0.';
            $headers = "From: ".$colabFromEmail . "\r\n";
            $headers .= "CC: ".$colabFromEmail . "\r\n";
            $headers .= "MIME-Version: 1.0\r\n";
            $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
            $message =  '<html><body>';
            $message .= '<p>Please click the link below to colaborate on this item with me.</p>';
            $message .= '<p>'.$chili_url.'</p>'; 
            $message .= '</body></html>';


            if (mail($to, $subject, $message, $headers)) {
                echo 
                '<script type="text/javascript">
                alert("Your link has been sent successfully.");
                </script>';
            } else {
                echo $this->getChiliEditorUrl();
            }

        } else {
            echo 'All fields are required.';
        }
    }
?>
<div class="right" style="margin-top: 20px;">
<button type="button" class="button btn-cart" onclick="toggleForm();">
<span><a href="#" id="colabButton" style="color: #fff;">Share</a></span>
</button>
        <div id="colabContainer" style="display:none; position: absolute;">
            <form action="" method="post" class="colabForm">
                <h2>Send to Collaborate</h2>
                <label>To: </label><br><input type="email" name="colabToEmail" ></input><br><br>
                <label>From: </label><br><input type="email" name="colabFromEmail" ></input><br><br>
                <input type="hidden" name="chili_url" id="chili_url" value="<?php echo $this->getChiliEditorUrl(); ?>" />

                <input type="submit" value="Send"/>
            </form>
            <form action="" method="" class="colabForm" id="loadURL" target="iframe">
                <h2>Load Document</h2>
                <label>Paste URL: </label><br><input type="text" name="colabURL" value="Paste URL Here" id="colabURL" />
                <br><br>
                <input type="button"  value="Load" onclick="go();"/>
            </form> 
        </div>  
<!-- Add this in if you want a "load" button. This only works if the window hasn't been navigated away from -->
<!-- <button type="button" class="button btn-cart">
<span><a href="<?php echo $this->getChiliEditorUrl(); ?>" target="iframe">Load</a></span>
</button> -->
</div>





<script type="text/javascript">

    var editorMode = '<?php echo $this->getMode(); ?>';
    var conceptUrl = '<?php echo $this->getConceptUrl(); ?>';
    var colaborateURL = '<?php echo $this->getChiliEditorUrl(); ?>';
    var cartUrl = '<?php echo $this->getCartUrl(); ?>';
    var productOptionCount = '<?php echo count($_product->getOptions()); ?>';
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    

function go(){
    var colabURL = document.getElementById('colabURL').value;
    colaborateURL = colabURL;
    document.getElementById('iframe').src = colaborateURL;
    document.getElementById("loadURL").reset();
    $('colabContainer').hide();
};

function toggleForm(){
    $('colabContainer').toggle();
}

    Event.observe(window, 'load', function() {
        // Populate product form
        populateForm('product_addtocart_form', productFormData);
        editorLoad('<?php echo Mage::app()->getRequest()->getActionName(); ?>',<?php echo Mage::helper('web2print')->getChiliIframeInversedHeight(); ?>);
    });

    if($('btn-concept')) {
        $('btn-concept').observe('click', function(e) {
            if($('productOptions')) {
                $('productOptions').setStyle({'display': 'block'});
            }

            if(productAddToCartForm.validator.validate() != true) {
                $('productOptions').setStyle({'display': 'block'});
            } else {
                if($('productOptions')) {
                    $('productOptions').setStyle({'display': 'none'});
                }

                try{
                    SaveDocument();
                }catch(error){
                    alert(error.message+"\nDocument save failed");
                    return;
                }

                data = $('product_addtocart_form').serialize();
                new Ajax.Request(conceptUrl, {
                    method: 'post',
                    parameters:data,
                    onSuccess: function(transport){
                        var responseObject = transport.responseText.evalJSON();
                        showNotification(responseObject.title, responseObject.content, '300', '120');
                    }
                });
            }
        });
    }

    if($('btn-cart')) {
        $('btn-cart').observe('click', function(e) {
            if($('productOptions')) {
                $('productOptions').setStyle({'display': 'block'});
            }
            if(productAddToCartForm.validator.validate() != true) {
                $('productOptions').setStyle({'display': 'block'});

            } else {
                if($('productOptions')) {
                    $('productOptions').setStyle({'display': 'none'});
                }

                try{
                    SaveDocument();
                }catch(error){
                    alert(error.message+"\nDocument save failed");
                    return;
                }

                productAddToCartForm.submit(document.getElementById('btn-cart'), cartUrl);
            }
        });
    }

    productAddToCartForm.submit = function(button, url) {
        var validated = true;

        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            form.action = url;
            form.submit();
        }
    }.bind(productAddToCartForm);   
</script>
</div>


<!--CHILI EDITOR FRAME STARTS HERE-->
<?php if ($this->getChiliEditorUrl()) : ?>
    <table width="90%" height="100%" style="margin-left:5%; margin-right:5%; margin-bottom:20px;">
        <tr valign="top">
            <?php if ($this->isChiliVariableHtmlFormEnabled()): ?>
                <td id="jsInput" runat="server" width="310px">
                    <div id="jsInputForm">
                        <h3><?php echo Mage::helper('web2print')->__('Document Content'); ?></h3>
                        <?php echo $this->getFormHtml(); ?>
                    </div>
                </td>
            <?php endif; ?>
            <td>
                <iframe frameborder="0" src="<?php echo $this->getChiliEditorUrl(); ?>" onload="GetEditor()" id="iframe" width="100%" height="100%" name="iframe"></iframe>
            </td>
        </tr>
    </table>
<?php else :
    echo "<p>".$this->__("Service is currently not available. Please try again later.")."</p>";
endif; ?>
</div>




