<?php
/**
 * Product Units and Quantities
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitunits
 * @version      1.0.11
 * @license:     0JdTQfDMswel7fbpH42tkXIHe3fixI4GH3daX0aDVf
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<script type="text/javascript">
    function showRegistries(link){
        baseRegistryLink = link;
    <?php if ($this->getEvents()->count() > 1): ?>
        $('adjgiftreg_popup').show();
    <?php else: ?>
        addToGiftRegistry(0);
    <?php endif ?>
        aitunitsForm_productQty.send(link,'giftregistry','0');
        return false;
    }
</script>