<?php
/**
 * All-In-One Checkout v1.0.15 : All-In-One Checkout v1.0.15 (OPCB Unit)
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitcheckout / Aitoc_Aitcheckout
 * @version      1.0.15 - 1.4.15
 * @license:     jC7sr77MwqoHj2SDR8w4YXR3o3w7irXLNFUdRYpgyc
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<div id="checkout-subscribe-newsletter">
    <input type="checkbox" name="newsletter" value="1" title="<?php echo Mage::helper('customer')->__('Subscribe to newsletter') ?>" id="newsletter" onchange="" class="checkbox" />
    <label for="newsletter"><?php echo Mage::helper('customer')->__('Subscribe to newsletter') ?></label>
</div>