<?php
    $item = $this->getItem();  
    $varNum = $this->getVarNum();
    $display_none = (isset($item['visible']) && $item['visible']) ? 'style="display:none;"' : '';

    $displayName = (String)$item->attributes()->displayName;
?>
<tr <?php echo $display_none ?> >
    <td class="label"><?php echo Mage::helper('web2print')->__($displayName); ?></td>
    <td>
        <select class="editor_select" name="<?php echo $varNum;?>" id="<?php echo "var_".$item->attributes()->name?>" width="100%">
            <?php foreach($item->listItems->item as $option){?>
                <option <?php if((string)$option->attributes()->id== (string)$item->attributes()->value):?> selected="selected" <?php endif;?> id='<?php echo $option->attributes()->id;?>' value="<?php echo $option->attributes()->id;?>"><?php echo $option->attributes()->displayValue;?></option>
            <?php }  ?>
        </select>        
    </td>
</tr>



