<?php
    $item = $this->getItem()->attributes();   
    $varNum = $this->getVarNum();
    $display_none = (isset($item['visible']) && $item['visible']) ? 'style="display:none;"' : '';

    $displayName = (String)$item->displayName;
?>

<tr <?php echo $display_none ?> >
    <td class="label"><?php echo Mage::helper('web2print')->__($displayName);?></td>
    <td><input class="editor_input" id='<?php echo "var_".$item->name?>' type="text" name="<?php echo $varNum;?>" value="<?php echo $item->value;?>" width="100%"/></td>
</tr>