<?php
/**
 * All-In-One Checkout v1.0.15 : All-In-One Checkout v1.0.15 (OPCB Unit)
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitcheckout / Aitoc_Aitcheckout
 * @version      1.0.15 - 1.4.15
 * @license:     jC7sr77MwqoHj2SDR8w4YXR3o3w7irXLNFUdRYpgyc
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<div id="aitgiftwrap-waiting" class="aitcheckout-wait" style="display:none"><img src="<?php echo Mage::getDesign()->getSkinUrl('images/opc-ajax-loader.gif'); ?>" /></div>
<script type="text/javascript">
//<![CDATA[

    aitCheckout.createStep('giftwrap',{
            }, {
                doCheckErrors : false,
                isLoadWaiting : true,
                isUpdateOnReload : false,
                isShowCartInCheckout : <?php echo $this->helper('aitcheckout')->isShowCartInCheckout()?'1':'0'?>,
                container: 'checkout-step-aitgiftwrap'
            }
    );
//]]>
</script>