<?php
    $item = $this->getItem()->attributes();   
    $varNum = $this->getVarNum();
    $display_none = (isset($item['visible']) && $item['visible']) ? 'style="display:none;"' : '';

    $displayName = (String)$item->displayName;
?>

<tr <?php echo $display_none ?>>
    <td class="label"><?php echo Mage::helper('web2print')->__($displayName);?></td>
    <td><input class="editor_checkbox" name="<?php echo $varNum;?>" type='checkbox' id='<?php echo "var_".$item->name?>' <?php if($item->value == "true"): echo " checked='checked' value='true' "; endif;?>  /></td>
</tr>